import {useRef,useState,useEffect} from 'react';
import {Routes,Route,NavLink,useNavigate,Navigate} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api,resetSession,setSession,type Session} from './api';
import {Capture} from './Capture';
import {Board} from './Board';
import {Publication} from './Publication';
import {Consent} from './Consent';
import {Audio} from './Audio';
export type Question={question_id:string;text:string;status:string;revision:number;subject_id:string;recipient_id?:string;review_due:string|null};
const states:Record<string,string>={received:'Vastaanotettu',scheduled:'Tarkistus sovittu',unanswered:'Odottaa vastausta',answered:'Vastattu'};
function Questions({items,staff,refresh}:{items:Question[];staff:boolean;refresh:()=>void}){
 const [due,setDue]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function act(q:Question,schedule:boolean){setBusy(true);setError('');try{await api(`/staff/questions/${q.question_id}/${schedule?'schedule':'mark-unanswered'}`,schedule?{assigned_to:'staff',review_due:new Date(due).toISOString()}:{reason_code:'awaiting_confirmation'},q.revision);refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <section><h2>{staff?'2 · Hoitajan kysymysjono':'Omat kysymykset'}</h2>{error&&<p role="alert">{error}</p>}{staff&&<label>Tarkistuksen aika (laitteen paikallinen aika)<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label>}{items.length===0&&<p>Ei kysymyksiä.</p>}{items.map(q=><article key={q.question_id}><p>{q.text}</p><span className="badge">{states[q.status]}</span><p className="muted">{q.review_due?new Date(q.review_due).toLocaleString('fi-FI',{timeZone:'Europe/Helsinki'}):'Tarkistuksen aikaa ei ole vielä sovittu.'}</p>{staff&&q.status!=='answered'&&<div className="row"><button disabled={!due||busy} onClick={()=>void act(q,true)}>Sovi tarkistus</button><button disabled={busy} onClick={()=>void act(q,false)}>Jätä odottamaan</button></div>}</article>)}</section>;
}
function Composer({refresh}:{refresh:()=>void}){
 const [text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const pending=useRef({text:'',key:''});
 async function send(){setBusy(true);setError('');if(pending.current.text!==text)pending.current={text,key:crypto.randomUUID()};try{await api('/family/residents/aino/questions',{text},undefined,undefined,pending.current.key);setText('');pending.current={text:'',key:''};refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <section><h2>Kysy hoitajalta</h2><p>Ei kiireellisiin asioihin. Käytä hoitopaikan vahvistettua yhteydenottotapaa.</p><label>Kysymys<textarea maxLength={2000} value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={busy||!text.trim()} onClick={()=>void send()}>Lähetä kysymys</button>{error&&<p role="alert">{error}</p>}</section>;
}
export function App(){
 const [online,setOnline]=useState(navigator.onLine);useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 const [viewer,saveSession]=useState<Session|null>(null),[locale,setLocale]=useState('fi'),[error,setError]=useState(''),[generation,setGeneration]=useState(0);const serial=useRef(0);const queryClient=useQueryClient();const navigate=useNavigate();
 async function login(actor:string){const current=++serial.current;resetSession();queryClient.clear();saveSession(null);setError('');setGeneration(n=>n+1);try{const s=await api<Session>('/demo/session',{demo_actor_id:actor});if(current!==serial.current)return;setSession(s);saveSession(s);navigate(s.role==='family'?'/family/residents/aino':'/staff/queue');}catch(e){if(current===serial.current)setError(String(e));}}
 const query=useQuery({queryKey:['questions',generation,viewer?.actor_id,locale],enabled:!!viewer,queryFn:()=>api<{items:Question[]}>(viewer?.role==='family'?'/family/residents/aino/questions':'/staff/question-queue'),refetchInterval:5000});
 const questions=query.isError||!online?[]:query.data?.items??[];const refresh=()=>{void query.refetch();};
 return <><header><div><span className="eyebrow">MEDIPENCIL</span><div className="brand">Päivän kuulumiset</div></div><span className="badge light">SYNTHETIC DEMO · paikallinen testi</span></header><main><div className="toolbar"><nav aria-label="Demo-käyttäjä">{['liisa','mikko','staff'].map(a=><button className={viewer?.actor_id===a?'selected':'secondary'} key={a} onClick={()=>void login(a)}>{a==='staff'?'Koskinen':a==='liisa'?'Liisa':'Mikko'}</button>)}</nav><p>Nykyinen käyttäjä: <strong>{viewer?.display_name??'Valitse käyttäjä'}</strong></p></div><p className="notice">Paikallinen demosessio · Aino (synteettinen) · Ei tuotantokäyttöön</p>{error&&<p role="alert">{error}</p>}{(query.isError||!online)&&<p role="alert">Yhteys tai käyttöoikeus muuttui. Kysymykset on piilotettu.</p>}{viewer?.role==='staff'&&<nav className="tabs" aria-label="Hoitajan työvaiheet"><NavLink to="/staff/queue">Kysymykset</NavLink><NavLink to="/staff/residents/aino/capture">Kirjaa ja julkaise</NavLink><NavLink to="/staff/residents/aino/consent">Suostumukset</NavLink></nav>}{!viewer&&<section><h1>Tervetuloa</h1><p>Valitse demokäyttäjä nähdäksesi hänelle sallitun näkymän.</p><p>Perheen kysymys kulkee hoitajalle. Vain tarkistettu ja julkaistu tieto palaa perheelle.</p></section>}{viewer&&<Routes><Route path="/family/residents/aino" element={viewer.role==='family'?<><label className="locale">Kieli<select aria-label="Kieli" value={locale} onChange={e=>setLocale(e.target.value)}><option value="fi">Suomi</option><option value="sv">Svenska — ei vielä saatavilla</option></select></label><Board key={generation} locale={locale}/><Composer key={'composer-'+generation} refresh={refresh}/><Questions items={questions} staff={false} refresh={refresh}/></>:<Navigate to="/staff/queue"/>}/><Route path="/staff/queue" element={viewer.role==='staff'?<Questions items={questions} staff refresh={refresh}/>:<Navigate to="/family/residents/aino"/>}/><Route path="/staff/residents/aino/capture" element={viewer.role==='staff'?<><Capture key={generation} questions={questions.filter(q=>q.status!=='answered')} onApproved={refresh}/><Publication key={'pub-'+generation}/><Audio key={'audio-'+generation}/></>:<Navigate to="/family/residents/aino"/>}/><Route path="/staff/residents/aino/consent" element={viewer.role==='staff'?<Consent key={generation}/>:<Navigate to="/family/residents/aino"/>}/><Route path="*" element={<Navigate to={viewer.role==='staff'?'/staff/queue':'/family/residents/aino'}/>}/></Routes>}</main><footer>Suomen kielen asiantuntija-arvio: odottaa · AI ei käytössä · Näyttöajat Europe/Helsinki</footer></>;
}
