import {useUiLanguage,languageLocales} from './UiLanguage';
import {useEffect,useState,useRef} from 'react';
import mikkoPortrait from './assets/mikko-portrait.jpg';
import portraitReference from './assets/pitch-care-reference.png';
import {CareComparison} from './CareComparison';
import {api} from './api';
import {DateRange,recentPeriod,periodDates} from './DateRange';
import {dailyOverview,careDay,type BoardData} from './dailyUpdate';
import {ForkKnife,Pill,PersonSimpleWalk,Tree,Bed,ChatCircle} from '@phosphor-icons/react';
const topicIcons=[ForkKnife,Pill,PersonSimpleWalk,Tree,Bed,ChatCircle];
const labels:Record<string,string>={meals:'Ruokailu',medication:'Lääkitys',movement:'Liikkuminen',outdoors:'Ulkoilu',sleep:'Uni',care_contact:'Yhteydenotto',not_shared:'Ei jaettu sinulle',no_record:'Ei kirjattua tietoa',awaiting_review:'Odottaa tarkistusta',plan:'Suunnitelma · ei toteutumisen vahvistusta',unattributed_statement:'Kertomus — puhuja tuntematon',resident_statement:'Asukas kertoi',staff_observation:'Hoitajan havainto',sensor_observation:'Sensorihavainto — ei hoitajan vahvistus'};
const emptyLabels:Record<string,string>={not_shared:'Tätä tietoa ei ole jaettu sinulle.',no_record:'Tästä aiheesta ei ole julkaistua tietoa.',awaiting_review:'Tieto odottaa tarkistusta ja julkaisua.'};
export function Board({locale,onAsk}:{locale:string;onAsk:(text:string)=>void}){
 const {tr,language}=useUiLanguage();
 const lastPublication=useRef<string|null>(null);
 const [period,setPeriod]=useState(()=>recentPeriod(3));
 const [showAll,setShowAll]=useState(false);
 const [selectedDay,setSelectedDay]=useState(''),[clock,setClock]=useState(()=>new Date());
 const [board,setBoard]=useState<BoardData|null>(null),[error,setError]=useState(''),[evidence,setEvidence]=useState('');
 useEffect(()=>{let active=true;setBoard(null);setEvidence('');async function read(){try{const b=await api<BoardData>('/family/residents/aino/board?lang='+locale);if(active&&navigator.onLine){setClock(new Date());if(b.publication_id!==lastPublication.current)setEvidence('');lastPublication.current=b.publication_id;setBoard(b);setError('');}}catch{if(active){setBoard(null);setEvidence('');setError("Yhteys tai käyttöoikeus muuttui. Tiedot on piilotettu.");}}}const offline=()=>{setBoard(null);setEvidence('');setError("Verkkoyhteys katkesi. Tiedot on piilotettu.");};window.addEventListener('offline',offline);window.addEventListener('online',read);void read();const timer=setInterval(()=>void read(),5000);return()=>{active=false;clearInterval(timer);window.removeEventListener('offline',offline);window.removeEventListener('online',read);};},[locale]);
 async function show(id:string){setEvidence('');try{const e=await api<{excerpt:string;source_label:string;occurred_at:string}>('/family/items/'+id+'/evidence');setEvidence(`${e.source_label}: ${e.excerpt} (${new Date(e.occurred_at).toLocaleString(languageLocales[language],{timeZone:'Europe/Helsinki'})})`);}catch{setEvidence(tr("Lähde ei ole enää saatavilla."));}}
 const overview=board?dailyOverview(board,clock,periodDates(period)):null;
 const formatDay=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString(languageLocales[language],{timeZone:'Europe/Helsinki',month:'short',day:'numeric',weekday:'short'});
 const unavailable=board?.language_state==='unavailable';
 const shared=board?.tiles.some(t=>t.display_state!=='not_shared');
 return <section className="board daily-board" aria-label={tr("Ainon päivän kuulumiset")}>
  <div className="daily-heading"><figure className="person-identity"><span className="reference-portrait aino-portrait" role="img" aria-label={tr('Aino 시연 사진')}><img src={portraitReference} alt=""/></span><figcaption>Aino</figcaption></figure><div><p className="daily-eyebrow">{tr('오늘의 일상을 함께')}</p><h1>{tr("Ainon päivän kuulumiset")}</h1><p>{formatDay(careDay(clock))} · {tr('보호자에게 전하는 안부')}</p><small className="muted">{tr('시연용 인물 사진')}</small></div>{board&&<figure className="person-identity guardian-identity">{board.viewer.actor_id==='liisa'?<span className="reference-portrait liisa-portrait" role="img" aria-label={tr('Liisa 시연 사진')}><img src={portraitReference} alt=""/></span>:board.viewer.actor_id==='mikko'?<img className="mikko-portrait" src={mikkoPortrait} alt={tr('Mikko 시연 사진')}/>:<span className="guardian-initial" aria-hidden="true">{board.viewer.display_name.slice(0,1)}</span>}<figcaption>{board.viewer.display_name}({tr('보호자')})</figcaption></figure>}</div>
  <nav className="daily-links" aria-label={tr('안부 바로가기')}><a href="#daily-details">{tr('일상 살펴보기')}</a><a href="#day-comparison">{tr('어제와 비교')}</a><a href="#recent-days">{tr('기간별 안부')}</a><a href="#ask-nurse">{tr('간호사에게 질문')}</a><a href="#question-board">{tr('내 질문과 답글')}</a></nav>
  {error?<p role="alert">{tr(error)}</p>:!board?<p role="status">{tr('안부를 불러오는 중입니다.')}</p>:unavailable?<p>{tr("Valitun kielen julkaisu ei ole saatavilla. Käyttäjä ja oikeudet pysyvät samoina.")}</p>:<>
   <div className="daily-summary" data-testid="daily-summary"><h2>{tr(!shared?'현재 공유된 항목이 없습니다.':overview?.hasToday?'오늘 날짜의 안부가 공유되었습니다.':'오늘의 안부를 기다리고 있어요.')}</h2><p>{tr(overview?.hasToday?'간호사가 검토한 내용을 항목별로 살펴보세요. 계획과 실행 여부는 각 기록에 표시됩니다.':'새 소식이 없다는 이유만으로 상태가 좋거나 나쁘다고 판단하지 않습니다.')}</p>{overview?.newest&&!overview.hasToday&&<p>{tr('가장 최근 기록일')}: {formatDay(careDay(overview.newest.observed_at))}</p>}{board.published_at&&<p className="muted">{tr('마지막 공유')}: {new Date(board.published_at).toLocaleString(languageLocales[language],{timeZone:'Europe/Helsinki'})}</p>}</div>
   <CareComparison board={board} now={clock} onAsk={onAsk} onEvidence={id=>void show(id)}/><div id="daily-details" className="daily-details"><DateRange value={period} onChange={p=>{setPeriod(p);setSelectedDay('');setShowAll(true);setEvidence('');}}/><div className="daily-details-heading"><h2>{tr('일상 살펴보기')}</h2>{selectedDay&&<button onClick={()=>setSelectedDay('')}>{tr('날짜 선택 해제')}</button>}</div><p className="muted">{selectedDay?formatDay(selectedDay):tr(showAll?'현재 공개된 기록입니다. 각 기록의 날짜를 확인해 주세요.':'항목별 최신 기록입니다. 오늘 이전의 기록은 날짜를 확인해 주세요.')}</p>{!selectedDay&&<button className="history-toggle" aria-pressed={showAll} onClick={()=>setShowAll(!showAll)}>{tr(showAll?'최신 기록만 보기':'전체 공개 기록 보기')}</button>}<div className="grid">{board.tiles.map((t,index)=>{const Icon=topicIcons[index];const eligible=t.items.filter(i=>{const d=careDay(i.observed_at);return selectedDay?d===selectedDay:d>=period.start&&d<=period.end;}).sort((a,b)=>new Date(b.observed_at).getTime()-new Date(a.observed_at).getTime());const items=selectedDay||showAll?eligible:eligible.slice(0,1);return <article key={t.topic} data-state={items.length?'published':t.display_state} className={'daily-topic daily-topic-'+t.topic}><div className="tile-heading"><h2><Icon size={24} weight="duotone" aria-hidden="true"/>{tr(labels[t.topic])}</h2><span className="badge" data-state={items.length?'published':t.display_state}>{tr(items.length?'Julkaistu':labels[t.display_state==='available'?'no_record':t.display_state])}</span></div>{items.length===0?<p className="tile-empty">{tr(selectedDay&&t.display_state!=='not_shared'?'이 날짜에 공개된 기록이 없습니다.':emptyLabels[t.display_state]??labels[t.display_state==='available'?'no_record':t.display_state])}</p>:items.map(i=><div className="daily-entry" key={i.item_id}><p>{i.statement}</p><p className="muted"><span className="claim-label" data-state={i.claim_type}>{tr(labels[i.claim_type])}</span> · {new Date(i.observed_at).toLocaleString(languageLocales[language],{timeZone:'Europe/Helsinki'})}</p><button onClick={()=>void show(i.item_id)}>{tr("Näytä lähde")}</button></div>)}</article>;})}</div></div>
   <div id="recent-days" className="recent-days"><h2>{tr('선택 기간의 안부')}</h2><p>{tr('날짜를 선택해 그날 공유된 내용을 살펴보세요. 기록 유무는 건강 상태의 변화가 아닙니다.')}</p><div className="recent-day-grid">{overview?.days.map(day=><button key={day.date} aria-pressed={selectedDay===day.date} onClick={()=>{setSelectedDay(selectedDay===day.date?'':day.date);document.getElementById('daily-details')?.scrollIntoView({behavior:'smooth'});}}><time dateTime={day.date}>{formatDay(day.date)}</time>{day.date===overview.today&&<strong>{tr('오늘')}</strong>}<span>{day.topics.length?day.topics.map(t=>tr(labels[t])).join(' · '):tr('공개된 기록 없음')}</span><span className="daily-day-action">{tr('이날의 안부 보기')}</span></button>)}</div></div>
  </>}
  {evidence&&<aside aria-label={tr("Lähde")}><p>{evidence}</p><button onClick={()=>setEvidence('')}>{tr("Sulje lähde")}</button></aside>}
  <p className="muted">{tr("Vain hyväksytty ja sinulle sallittu tieto.")}</p>
 </section>;
}
