import {useEffect,useState} from 'react';
import {api} from './api';
type Item={item_id:string;statement:string;claim_type:string;observed_at:string;action_status:string|null};
type BoardData={language_state:string;published_at:string|null;tiles:{topic:string;display_state:string;items:Item[]}[]};
const labels:Record<string,string>={meals:'Ruokailu',medication:'Lääkitys',movement:'Liikkuminen',outdoors:'Ulkoilu',sleep:'Uni',care_contact:'Yhteydenotto',not_shared:'Ei jaettu sinulle',no_record:'Ei kirjattua tietoa',awaiting_review:'Odottaa tarkistusta',plan:'Suunnitelma · ei toteutumisen vahvistusta',resident_statement:'Asukas kertoi',staff_observation:'Hoitajan havainto'};
export function Board({locale}:{locale:string}){
 const [board,setBoard]=useState<BoardData|null>(null),[error,setError]=useState(''),[evidence,setEvidence]=useState('');
 useEffect(()=>{let active=true;setBoard(null);setEvidence('');async function read(){try{const b=await api<BoardData>('/family/residents/aino/board?lang='+locale);if(active){setBoard(b);setError('');}}catch{if(active){setBoard(null);setEvidence('');setError('Yhteys tai käyttöoikeus muuttui. Tiedot on piilotettu.');}}}void read();const timer=setInterval(()=>void read(),5000);return()=>{active=false;clearInterval(timer);};},[locale]);
 async function show(id:string){setEvidence('');try{const e=await api<{excerpt:string;source_label:string;occurred_at:string}>('/family/items/'+id+'/evidence');setEvidence(`${e.source_label}: ${e.excerpt} (${new Date(e.occurred_at).toLocaleString('fi-FI',{timeZone:'Europe/Helsinki'})})`);}catch{setEvidence('Lähde ei ole enää saatavilla.');}}
 return <section><h1>Ainon päivän kuulumiset</h1><p>Vain hyväksytty ja sinulle sallittu tieto.</p>{error&&<p role="alert">{error}</p>}{board?.language_state==='unavailable'?<p>Valitun kielen julkaisu ei ole saatavilla. Käyttäjä ja oikeudet pysyvät samoina.</p>:<div className="grid">{board?.tiles.map(t=><article key={t.topic}><h2>{labels[t.topic]}</h2>{t.items.length===0?<p>{labels[t.display_state]}</p>:t.items.map(i=><div key={i.item_id}><p>{i.statement}</p><p className="muted">{labels[i.claim_type]} · {new Date(i.observed_at).toLocaleString('fi-FI',{timeZone:'Europe/Helsinki'})}</p><button onClick={()=>void show(i.item_id)}>Näytä lähde</button></div>)}</article>)}</div>}{evidence&&<aside aria-label="Lähde"><p>{evidence}</p><button onClick={()=>setEvidence('')}>Sulje lähde</button></aside>}<p className="muted">Suora syöttö · STT ohitettu · AI ei käytössä</p></section>;
}
