import {useUiLanguage,languageLocales} from './UiLanguage';
import {useEffect,useState,useRef} from 'react';
import {api} from './api';
import type {components} from './generated-api';
type BoardData=components['schemas']['FamilyBoardDTO'];
const labels:Record<string,string>={meals:'Ruokailu',medication:'Lääkitys',movement:'Liikkuminen',outdoors:'Ulkoilu',sleep:'Uni',care_contact:'Yhteydenotto',not_shared:'Ei jaettu sinulle',no_record:'Ei kirjattua tietoa',awaiting_review:'Odottaa tarkistusta',plan:'Suunnitelma · ei toteutumisen vahvistusta',unattributed_statement:'Kertomus — puhuja tuntematon',resident_statement:'Asukas kertoi',staff_observation:'Hoitajan havainto',sensor_observation:'Sensorihavainto — ei hoitajan vahvistus'};
const emptyLabels:Record<string,string>={not_shared:'Tätä tietoa ei ole jaettu sinulle.',no_record:'Tästä aiheesta ei ole julkaistua tietoa.',awaiting_review:'Tieto odottaa tarkistusta ja julkaisua.'};
export function Board({locale}:{locale:string}){
 const {tr,language}=useUiLanguage();
 const lastPublication=useRef<string|null>(null);
 const [board,setBoard]=useState<BoardData|null>(null),[error,setError]=useState(''),[evidence,setEvidence]=useState('');
 useEffect(()=>{let active=true;setBoard(null);setEvidence('');async function read(){try{const b=await api<BoardData>('/family/residents/aino/board?lang='+locale);if(active){if(b.publication_id!==lastPublication.current)setEvidence('');lastPublication.current=b.publication_id;setBoard(b);setError('');}}catch{if(active){setBoard(null);setEvidence('');setError("Yhteys tai käyttöoikeus muuttui. Tiedot on piilotettu.");}}}const offline=()=>{setBoard(null);setEvidence('');setError("Verkkoyhteys katkesi. Tiedot on piilotettu.");};window.addEventListener('offline',offline);window.addEventListener('online',read);void read();const timer=setInterval(()=>void read(),5000);return()=>{active=false;clearInterval(timer);window.removeEventListener('offline',offline);window.removeEventListener('online',read);};},[locale]);
 async function show(id:string){setEvidence('');try{const e=await api<{excerpt:string;source_label:string;occurred_at:string}>('/family/items/'+id+'/evidence');setEvidence(`${e.source_label}: ${e.excerpt} (${new Date(e.occurred_at).toLocaleString(languageLocales[language],{timeZone:'Europe/Helsinki'})})`);}catch{setEvidence(tr("Lähde ei ole enää saatavilla."));}}
 return <section className="board"><h1>{tr("Ainon päivän kuulumiset")}</h1><p>{tr("Vain hyväksytty ja sinulle sallittu tieto.")}</p>{error&&<p role="alert">{tr(error)}</p>}{board?.language_state==='unavailable'?<p>{tr("Valitun kielen julkaisu ei ole saatavilla. Käyttäjä ja oikeudet pysyvät samoina.")}</p>:<div className="grid">{board?.tiles.map(t=><article key={t.topic} data-state={t.items.length?'published':t.display_state}><div className="tile-heading"><h2>{tr(labels[t.topic])}</h2><span className="badge" data-state={t.items.length?'published':t.display_state}>{tr(t.items.length?'Julkaistu':labels[t.display_state])}</span></div>{t.items.length===0?<p className="tile-empty">{tr(emptyLabels[t.display_state]??labels[t.display_state])}</p>:t.items.map(i=><div key={i.item_id}><p>{i.statement}</p><p className="muted"><span className="claim-label" data-state={i.claim_type}>{tr(labels[i.claim_type])}</span> · {new Date(i.observed_at).toLocaleString(languageLocales[language],{timeZone:'Europe/Helsinki'})}</p><button onClick={()=>void show(i.item_id)}>{tr("Näytä lähde")}</button></div>)}</article>)}</div>}{evidence&&<aside aria-label={tr("Lähde")}><p>{evidence}</p><button onClick={()=>setEvidence('')}>{tr("Sulje lähde")}</button></aside>}<p className="muted">{tr("Tallennettu julkaisu (CACHED) · Tarkistetut lähteet · Julkaisu ei tuota uutta AI-tekstiä")}</p></section>;
}
