import {useState} from 'react';
import {api} from './api';
export type Segment={segment_id:string;text:string;type:string;speaker:string;required_scopes:string[];evidence_refs:unknown[]};
export type RecordData={record_id:string;version:number;revision:number;status:string;segments:Segment[];answer_candidates:{candidate_id:string;question_id:string}[]};
type Cap={capture_id:string;revision:number};
export function Capture({questions,onApproved}:{questions:{question_id:string;text:string}[];onApproved:()=>void}){
 const [text,setText]=useState(''),[kind,setKind]=useState('statement'),[speaker,setSpeaker]=useState('resident'),[scope,setScope]=useState('health_context'),[question,setQuestion]=useState(''),[record,setRecord]=useState<RecordData|null>(null),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function create(){setBusy(true);setError('');try{let cap=await api<Cap>('/staff/residents/aino/captures',{input_mode:'text'});cap=await api<Cap>(`/staff/captures/${cap.capture_id}/text`,{occurred_at:new Date().toISOString(),utterances:[{speaker,text,type:kind,required_scopes:scope.split(',')}]},cap.revision);const job=await api<{result_ref:{id:string;version:number}}>(`/staff/captures/${cap.capture_id}/drafts`,{question_ids:question?[question]:[]},cap.revision);setRecord(await api<RecordData>(`/staff/records/${job.result_ref.id}?version=${job.result_ref.version}`));setChecked(false);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function approve(){if(!record||!checked)return;setBusy(true);try{const r=await api<RecordData>(`/staff/records/${record.record_id}/approve`,{version:record.version,segment_reviews:record.segments.map(s=>({segment_id:s.segment_id,meaning_checked:checked,speaker_checked:checked,negation_and_tense_checked:checked,numbers_checked:checked,scopes_checked:checked})),candidate_reviews:record.answer_candidates.map(c=>({candidate_id:c.candidate_id,accepted:checked,sufficient_answer_checked:checked}))},record.revision);setRecord(r);onApproved();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <section><h2>3 · Kirjaa ja tarkista</h2><p>Suora tekstisyöttö · STT ohitettu · AI ei käytössä. Vain itsenäinen synteettinen aineisto.</p>{error&&<p role="alert">{error}</p>}<label>Liitä omaan kysymykseen<select value={question} onChange={e=>setQuestion(e.target.value)}><option value="">Ei vastausliitosta</option>{questions.map(q=><option key={q.question_id} value={q.question_id}>{q.text}</option>)}</select></label><label>Alkuperäinen teksti<textarea value={text} onChange={e=>setText(e.target.value)}/></label><div className="row"><label>Puhuja<select value={speaker} onChange={e=>setSpeaker(e.target.value)}><option value="resident">Asukas</option><option value="carer">Hoitaja</option><option value="unknown">Tuntematon</option></select></label><label>Tyyppi<select value={kind} onChange={e=>setKind(e.target.value)}><option value="statement">Kertomus</option><option value="observation">Havainto</option><option value="plan">Suunnitelma — ei toteutunut</option></select></label></div><label>Tiedon sisältö<select value={scope} onChange={e=>setScope(e.target.value)}><option value="health_context">Terveystieto</option><option value="outdoors">Ulkoilu</option><option value="outdoors,health_context">Ulkoilu ja terveystieto</option><option value="medication">Lääkitys</option><option value="sleep">Uni</option><option value="meals">Ruokailu</option><option value="movement">Liikkuminen</option><option value="care_contact">Yhteydenotto</option></select></label><button disabled={busy||!text.trim()} onClick={()=>void create()}>Luo tarkistettava luonnos</button>{record&&<article><h3>Kirjaus · {record.status}</h3>{record.segments.map(s=><p key={s.segment_id}>{s.text} <small>{s.type}</small></p>)}{record.status==='draft'&&<><label><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Tarkistin lähteen, merkityksen, puhujan, kiellot, aikamuodon, luvut, jakamisrajat ja vastauksen riittävyyden.</label><button disabled={busy||!checked} onClick={()=>void approve()}>Hyväksy kirjaus</button></>}<p>Kirjauksen hyväksyminen ei julkaise perheelle eikä muuta suostumusta.</p></article>}</section>;
}
