import {useUiLanguage} from './UiLanguage';
import {useState} from 'react';
import {api} from './api';
type Grant={recipient_id:string;version:number;scopes:string[]};
type Candidate={candidate_id:string;recipient_id:string;proposed_scopes:string[];disposition:string;revision:number;utterance_ref:{source_id:string;source_version:number;utterance_id:string}};
type Source={source_id:string;version:number;payload:{utterances?:{utterance_id:string;text:string}[]}};
export function Consent(){
 const {tr}=useUiLanguage();
 const [grants,setGrants]=useState<Grant[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[sources,setSources]=useState<Source[]>([]),[selected,setSelected]=useState(''),[checked,setChecked]=useState(false),[error,setError]=useState(''),[revoke,setRevoke]=useState('outdoors');
 const options=sources.flatMap(s=>(s.payload.utterances??[]).map(u=>({label:u.text,ref:{kind:'source',source_id:s.source_id,source_version:s.version,utterance_id:u.utterance_id}})));
 async function load(){try{const c=await api<{grants:Grant[];candidates:Candidate[]}>('/staff/residents/aino/consents');const s=await api<{items:Source[]}>('/staff/residents/aino/sources');setGrants(c.grants);setCandidates(c.candidates);setSources(s.items);}catch(e){setError(String(e));}}
 async function create(){if(selected==='')return;try{await api('/staff/residents/aino/consent-candidates',{recipient_id:'mikko',proposed_scopes:['outdoors'],utterance_ref:options[Number(selected)].ref});setChecked(false);await load();}catch(e){setError(String(e));}}
 async function confirm(c:Candidate){if(!checked)return;try{await api(`/staff/consent-candidates/${c.candidate_id}/confirm`,{recipient_id:c.recipient_id,confirmed_scopes:c.proposed_scopes,expected_consent_version:grants.find(g=>g.recipient_id===c.recipient_id)?.version??0,speaker_and_scope_checked:checked},c.revision);setChecked(false);await load();}catch(e){setError(String(e));}}
 async function remove(g:Grant){if(!checked)return;try{await api(`/staff/residents/aino/consents/${g.recipient_id}/revoke`,{scopes:[revoke],expected_consent_version:g.version,reason_code:'staff_reviewed_revocation'});setChecked(false);await load();}catch(e){setError(String(e));}}
 return <section><h2>{tr("5 · Tarkista suostumus")}</h2><p>{tr("Aino → Mikko. Ulkoilun jakaminen ei salli terveystietoja, lääkitystä tai unta.")}</p><button onClick={()=>void load()}>{tr("Lataa suostumukset ja lähteet")}</button>{error&&<p role="alert">{error}</p>}{grants.map(g=><p key={g.recipient_id}>{g.recipient_id} · v{g.version}: {g.scopes.join(', ')||tr("Ei jaettuja tietoja")}</p>)}<label>{tr("Suostumuksen lähdelausuma")}<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{tr("Valitse tarkistettava lausuma")}</option>{options.map((o,i)=><option key={i} value={String(i)}>{o.label}</option>)}</select></label><button disabled={selected===''} onClick={()=>void create()}>{tr("Luo ehdokas: Mikko + ulkoilu")}</button><label><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>{tr("Vahvistan henkilöt, lähdelausuman ja alla näytetyn jakamismuutoksen.")}</label>{candidates.filter(c=>c.disposition==='pending').map(c=><article key={c.candidate_id}><p>{tr("Lisättävä:")} {c.recipient_id} → {c.proposed_scopes.join(', ')}</p><p>{options.find(o=>o.ref.utterance_id===c.utterance_ref.utterance_id)?.label}</p><button disabled={!checked} onClick={()=>void confirm(c)}>{tr("Vahvista rajattu jakaminen")}</button></article>)}<label>{tr("Peruttava tieto")}<select value={revoke} onChange={e=>setRevoke(e.target.value)}>{['outdoors','health_context','medication','sleep','meals','movement','care_contact'].map(s=><option key={s}>{s}</option>)}</select></label>{grants.map(g=><button key={g.recipient_id} disabled={!checked||!g.scopes.includes(revoke)} onClick={()=>void remove(g)}>{tr("Peru")} {g.recipient_id}: {revoke}</button>)}<p>{tr("Paikallinen demomenettely. Oikeudellista pätevyyttä ei ole vahvistettu.")}</p></section>;
}
