import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api} from './api';
import {useUiLanguage,languageLocales} from './UiLanguage';

type Event={event_id:string;revision:number;state:string;external_id:string;source_version:number;title:string;starts_at:string;location:string;details:string;status:'scheduled'|'cancelled';required_scopes:string[];acknowledged_at?:string|null;deliveries?:{recipient_id:string;acknowledged_at:string|null;visible:boolean}[]};
const scopeNames:Record<string,string>={care_contact:'돌봄 연락',health_context:'건강 정보',medication:'복약',meals:'식사',movement:'이동',outdoors:'야외 활동',sleep:'수면'};
export function FamilyEvents({staff,actor}:{staff:boolean;actor:string}){
 const {tr,language}=useUiLanguage();
 const [online,setOnline]=useState(navigator.onLine),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [reviewed,setReviewed]=useState<Record<string,boolean>>({}),[recipients,setRecipients]=useState<Record<string,string[]>>({});
 const [draft,setDraft]=useState({external_id:'',source_version:1,title:'',starts_at:'',location:'',details:'',status:'scheduled',required_scopes:['care_contact','health_context']});
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 const query=useQuery({queryKey:['family-events',actor],queryFn:()=>api<{items:Event[]}>(`/${staff?'staff':'family'}/residents/aino/family-events`),refetchInterval:5000});
 const items=query.isError||!online?[]:query.data?.items??[];
 const date=(v:string)=>new Date(v).toLocaleString(languageLocales[language],{timeZone:'Europe/Helsinki'});
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');setMessage('');try{await action();await query.refetch();setMessage(tr('저장되었습니다.'));}catch(e){setError(String(e));}finally{setBusy(false);}}
 function sample(){const d=new Date();d.setDate(d.getDate()+2);d.setHours(10,0,0,0);setDraft({external_id:'synthetic-appointment-01',source_version:1,title:tr('합성 예시 · 정기 진료'),starts_at:new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16),location:tr('합성 병원 · 외래 1'),details:tr('가족에게 진료 일정을 안내합니다. 동행 여부는 가족확인사항에 남겨 주세요.'),status:'scheduled',required_scopes:['care_contact','health_context']});}
 function edit(e:Event){const d=new Date(e.starts_at);setDraft({external_id:e.external_id,source_version:e.source_version+1,title:e.title,starts_at:new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16),location:e.location,details:e.details,status:e.status,required_scopes:e.required_scopes});document.getElementById('event-import')?.scrollIntoView({behavior:'smooth'});}
 const unconfirmed=items.filter(e=>!e.acknowledged_at).length;
 return <section id="family-events" className="family-events" aria-label={tr('병원 주요 이벤트')}><div className="question-board-heading"><h2>{tr('가족확인사항')}</h2>{!staff&&<span role="status" className="badge">{tr('미확인 안내')} {unconfirmed}</span>}</div><h3>{tr('병원 주요 이벤트')}</h3><p className="muted">{tr('EMR 연동 컨셉 · 합성 데이터 · 실제 EMR 연결 없음')}</p><p>{tr('앱 안에서 확인하는 알림입니다. 문자·이메일·휴대폰 푸시는 발송하지 않습니다.')}</p>
 {staff&&<details className="event-import" id="event-import" open><summary>{tr('합성 EMR 일정 가져오기')}</summary><button type="button" onClick={sample} disabled={busy}>{tr('진료일정 예시 채우기')}</button><form onSubmit={e=>{e.preventDefault();void run(()=>api('/staff/residents/aino/family-events/import',{data_origin:'TEAM_SYNTHETIC',events:[{...draft,starts_at:new Date(draft.starts_at).toISOString()}]}));}}><div className="event-form-grid"><label>{tr('외부 일정 ID')}<input required maxLength={80} value={draft.external_id} onChange={e=>setDraft({...draft,external_id:e.target.value})}/></label><label>{tr('원본 버전')}<input type="number" min={1} required value={draft.source_version} onChange={e=>setDraft({...draft,source_version:Number(e.target.value)})}/></label><label>{tr('안내 제목')}<input required maxLength={160} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>{tr('일정 일시 (기기 현지 시간)')}<input type="datetime-local" required value={draft.starts_at} onChange={e=>setDraft({...draft,starts_at:e.target.value})}/></label><label>{tr('장소')}<input required maxLength={160} value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label><label>{tr('일정 상태')}<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="scheduled">{tr('예정')}</option><option value="cancelled">{tr('취소')}</option></select></label></div><label>{tr('가족 안내 내용')}<textarea required maxLength={2000} value={draft.details} onChange={e=>setDraft({...draft,details:e.target.value})}/></label><fieldset><legend>{tr('내용에 필요한 공유 범위')}</legend><div className="event-scopes">{Object.entries(scopeNames).map(([key,label])=><label key={key}><input type="checkbox" disabled={key==='care_contact'} checked={draft.required_scopes.includes(key)} onChange={e=>setDraft({...draft,required_scopes:e.target.checked?[...draft.required_scopes,key]:draft.required_scopes.filter(s=>s!==key)})}/>{tr(label)}</label>)}</div></fieldset><p className="muted">{tr('같은 ID의 상위 버전을 가져오면 기존 알림을 숨기고 재검토합니다. 진료·검사 정보에는 건강 정보 범위를 포함하세요.')}</p><button disabled={busy||!online}>{tr('가져와 검토 대기')}</button></form></details>}
 {(error||query.isError||!online)&&<p role="alert">{error?tr(error):tr('연결 또는 권한을 확인하세요. 알림은 숨겨졌습니다.')}</p>}{message&&<p role="status">{message}</p>}{query.isPending&&<p>{tr('불러오는 중…')}</p>}{!query.isPending&&!query.isError&&online&&items.length===0&&<p>{tr('현재 공유된 안내가 없습니다.')}</p>}
 <div className="event-list">{items.map(e=><article className="event-card" key={e.event_id} data-testid="family-event"><div className="question-post-meta"><span className="badge">{tr(e.status==='cancelled'?'일정 취소':'예정된 일정')}</span>{staff&&<span>{tr(e.state==='draft'?'검토 대기':'발행됨')}</span>}</div><h3>{e.title}</h3><p><time dateTime={e.starts_at}>{date(e.starts_at)} (Europe/Helsinki)</time> · {e.location}</p><p className="event-body">{e.details}</p><small>{tr('합성 원본')} · {e.external_id} · v{e.source_version}</small>{staff?<><p>{tr('공유 범위')}: {e.required_scopes.map(s=>tr(scopeNames[s])).join(', ')}</p>{e.state==='draft'?<><fieldset><legend>{tr('알림 받을 가족')}</legend>{['liisa','mikko'].map(id=><label key={id}><input type="checkbox" checked={(recipients[e.event_id]??[]).includes(id)} onChange={ev=>setRecipients({...recipients,[e.event_id]:ev.target.checked?[...(recipients[e.event_id]??[]),id]:(recipients[e.event_id]??[]).filter(x=>x!==id)})}/>{id==='liisa'?'Liisa':'Mikko'}</label>)}</fieldset><label className="event-review"><input type="checkbox" checked={!!reviewed[e.event_id+'-'+e.revision]} onChange={ev=>setReviewed({...reviewed,[e.event_id+'-'+e.revision]:ev.target.checked})}/>{tr('일정·내용·수신자·공유 범위를 확인했습니다.')}</label><button disabled={busy||!online||!reviewed[e.event_id+'-'+e.revision]||!(recipients[e.event_id]?.length)} onClick={()=>void run(()=>api(`/staff/family-events/${e.event_id}/publish`,{recipients:recipients[e.event_id],reviewed:true},e.revision))}>{tr('검토 완료 · 가족에게 알림')}</button></>:<button disabled={busy||!online} onClick={()=>void run(()=>api(`/staff/family-events/${e.event_id}/withdraw`,{},e.revision))}>{tr('알림 회수')}</button>}<button className="secondary" disabled={busy} onClick={()=>edit(e)}>{tr('일정 변경·취소 작성')}</button><ul>{e.deliveries?.map(d=><li key={d.recipient_id}>{d.recipient_id==='liisa'?'Liisa':'Mikko'} · {tr(!d.visible?'공개 중단':d.acknowledged_at?'가족 확인 완료':'가족 확인 대기')}{d.visible&&d.acknowledged_at&&` · ${date(d.acknowledged_at)}`}</li>)}</ul></>:e.acknowledged_at?<p className="event-ack">✓ {tr('확인했어요')} · {date(e.acknowledged_at)}</p>:<button disabled={busy||!online} onClick={()=>void run(()=>api(`/family/family-events/${e.event_id}/acknowledge`,{},e.revision))}>{tr('확인했어요')}</button>}</article>)}</div></section>;
}
