/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_demo_session_post"];
        /** Logout */
        delete: operations["logout_api_v1_demo_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who */
        get: operations["who_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Residents */
        get: operations["residents_api_v1_staff_residents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family/residents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Residents */
        get: operations["residents_api_v1_family_residents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family/residents/{s}/sharing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sharing */
        get: operations["sharing_api_v1_family_residents__s__sharing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family/residents/{s}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Questions */
        get: operations["questions_api_v1_family_residents__s__questions_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_family_residents__s__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/question-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue */
        get: operations["queue_api_v1_staff_question_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/questions/{q}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule */
        post: operations["schedule_api_v1_staff_questions__q__schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/questions/{q}/mark-unanswered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unanswered */
        post: operations["unanswered_api_v1_staff_questions__q__mark_unanswered_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture */
        post: operations["capture_api_v1_staff_residents__s__captures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/captures/{c}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Text */
        post: operations["text_api_v1_staff_captures__c__text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/captures/{c}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft */
        post: operations["draft_api_v1_staff_captures__c__drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/jobs/{j}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_v1_staff_jobs__j__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/records/{r}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record */
        get: operations["get_record_api_v1_staff_records__r__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/records/{r}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit */
        patch: operations["edit_api_v1_staff_records__r__draft_patch"];
        trace?: never;
    };
    "/api/v1/staff/records/{r}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_v1_staff_records__r__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_v1_staff_residents__s__sources_get"];
        put?: never;
        /** Source */
        post: operations["source_api_v1_staff_residents__s__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Actions */
        get: operations["actions_api_v1_staff_residents__s__actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/captures/{c}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capture */
        get: operations["get_capture_api_v1_staff_captures__c__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Status */
        get: operations["provider_status_api_v1_staff_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/emr-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review */
        get: operations["review_api_v1_staff_residents__s__emr_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/emr-review/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Bundle */
        post: operations["import_bundle_api_v1_staff_residents__s__emr_review_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/publication-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Context */
        get: operations["context_api_v1_staff_residents__s__publication_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/publications/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare */
        post: operations["prepare_api_v1_staff_publications_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/publications/{p}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pub */
        get: operations["get_pub_api_v1_staff_publications__p__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/publications/{p}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit */
        patch: operations["edit_api_v1_staff_publications__p__draft_patch"];
        trace?: never;
    };
    "/api/v1/staff/publications/{p}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_staff_publications__p__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family/residents/{s}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Board */
        get: operations["board_api_v1_family_residents__s__board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family/items/{item}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_v1_family_items__item__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/actions/{a}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_api_v1_staff_actions__a__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{role}/residents/{s}/family-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listing */
        get: operations["listing_api_v1__role__residents__s__family_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/family-events/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Events */
        post: operations["import_events_api_v1_staff_residents__s__family_events_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/family-events/{eid}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_staff_family_events__eid__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/family-events/{eid}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw */
        post: operations["withdraw_api_v1_staff_family_events__eid__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family/family-events/{eid}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge */
        post: operations["acknowledge_api_v1_family_family_events__eid__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_staff_residents__s__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/family/residents/{s}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_family_residents__s__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Consents */
        get: operations["list_consents_api_v1_staff_residents__s__consents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/consent-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Candidate */
        post: operations["candidate_api_v1_staff_residents__s__consent_candidates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/consent-candidates/{c}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_api_v1_staff_consent_candidates__c__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/consent-candidates/{c}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_v1_staff_consent_candidates__c__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/consents/{recipient}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke */
        post: operations["revoke_api_v1_staff_residents__s__consents__recipient__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/records/{r}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct */
        post: operations["correct_api_v1_staff_records__r__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/recording-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Permission */
        post: operations["permission_api_v1_staff_residents__s__recording_permissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/captures/{c}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_staff_captures__c__audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/captures/{c}/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe */
        post: operations["transcribe_api_v1_staff_captures__c__transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/captures/{c}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_staff_captures__c__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/captures/{c}/audio-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_staff_captures__c__audio_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/captures/{c}/retry-cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_staff_captures__c__retry_cleanup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/residents/{s}/sensor-observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sensor */
        post: operations["sensor_api_v1_staff_residents__s__sensor_observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/poc/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listing */
        get: operations["listing_api_v1_poc_comments_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_poc_comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Answer */
        Answer: {
            /** Question Id */
            question_id: string;
            /** Item Ids */
            item_ids: string[];
        };
        /** Approve */
        Approve: {
            /** Version */
            version: number;
            /** Segment Reviews */
            segment_reviews: components["schemas"]["SegmentReview"][];
            /** Candidate Reviews */
            candidate_reviews: components["schemas"]["CandidateReview"][];
        };
        /** Body_upload_api_v1_staff_captures__c__audio_post */
        Body_upload_api_v1_staff_captures__c__audio_post: {
            /** File */
            file: string;
        };
        /** Candidate */
        Candidate: {
            /** Recipient Id */
            recipient_id: string;
            /** Proposed Scopes */
            proposed_scopes: string[];
            /** Utterance Ref */
            utterance_ref: {
                [key: string]: unknown;
            };
        };
        /** CandidateReview */
        CandidateReview: {
            /** Candidate Id */
            candidate_id: string;
            /** Accepted */
            accepted: boolean;
            /** Sufficient Answer Checked */
            sufficient_answer_checked: boolean;
        };
        /** Capture */
        Capture: {
            /**
             * Input Mode
             * @enum {string}
             */
            input_mode: "text" | "audio";
            /**
             * Disclosure Ack
             * @default false
             */
            disclosure_ack: boolean;
            /** Recording Permission Ref */
            recording_permission_ref?: string | null;
        };
        /** CommentCreate */
        CommentCreate: {
            /** Reviewer Alias */
            reviewer_alias: string;
            /**
             * Screen
             * @enum {string}
             */
            screen: "general" | "family" | "questions" | "record" | "publication" | "consent";
            /** Body */
            body: string;
        };
        /** Correction */
        Correction: {
            /** Version */
            version: number;
            /** Reason Code */
            reason_code: string;
        };
        /** Draft */
        Draft: {
            /** Question Ids */
            question_ids?: string[];
            /**
             * Processing Mode
             * @default manual
             * @enum {string}
             */
            processing_mode: "manual" | "local";
        };
        /** Empty */
        Empty: Record<string, never>;
        /** Event */
        Event: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "enter" | "leave";
            /** At */
            at: string;
        };
        /** EventInput */
        EventInput: {
            /** External Id */
            external_id: string;
            /** Source Version */
            source_version: number;
            /** Title */
            title: string;
            /** Starts At */
            starts_at: string;
            /** Location */
            location: string;
            /** Details */
            details: string;
            /**
             * Status
             * @default scheduled
             * @enum {string}
             */
            status: "scheduled" | "cancelled";
            /** Required Scopes */
            required_scopes: string[];
        };
        /** EvidencePreviewDTO */
        EvidencePreviewDTO: {
            /** Item Id */
            item_id: string;
            /** Source Label */
            source_label: string;
            /** Occurred At */
            occurred_at: string;
            /** Excerpt */
            excerpt: string;
            /**
             * Evidence State
             * @constant
             */
            evidence_state: "valid";
        };
        /** FamilyBoardDTO */
        FamilyBoardDTO: {
            subject: components["schemas"]["Subject"];
            viewer: components["schemas"]["Person"];
            /**
             * Lang
             * @enum {string}
             */
            lang: "fi" | "sv" | "en";
            /** Display Timezone */
            display_timezone: string;
            /**
             * Board State
             * @enum {string}
             */
            board_state: "ready" | "awaiting_review" | "empty";
            /**
             * Language State
             * @enum {string}
             */
            language_state: "available" | "unavailable";
            /** Tiles */
            tiles: components["schemas"]["Tile"][];
            /** Answers */
            answers: components["schemas"]["Answer"][];
            /** Publication Id */
            publication_id: string | null;
            /** Published At */
            published_at: string | null;
            /** Can Ask */
            can_ask: boolean;
            /** Execution */
            execution: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Import */
        Import: {
            /**
             * Data Origin
             * @constant
             */
            data_origin: "TEAM_SYNTHETIC";
            /** Events */
            events: components["schemas"]["EventInput"][];
        };
        /** Input */
        Input: Record<string, never>;
        /** ItemReview */
        ItemReview: {
            /** Item Id */
            item_id: string;
            /** Meaning Checked */
            meaning_checked: boolean;
            /** Language Checked */
            language_checked: boolean;
            /** Evidence Checked */
            evidence_checked: boolean;
        };
        /** JobDTO */
        JobDTO: {
            /** Job Id */
            job_id: string;
            /** Job Type */
            job_type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "canceled";
            /** Result Ref */
            result_ref: {
                [key: string]: unknown;
            } | null;
            /** Progress Stage */
            progress_stage: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error Code */
            error_code: string | null;
            /** Retryable */
            retryable: boolean;
            /** Execution */
            execution: {
                [key: string]: unknown;
            };
        };
        /** Login */
        Login: {
            /** Demo Actor Id */
            demo_actor_id: string;
        };
        /** Meta */
        Meta: {
            /** Request Id */
            request_id: string;
            /** Server Time */
            server_time: string;
        };
        /** Page[QuestionDTO] */
        Page_QuestionDTO_: {
            /** Items */
            items: components["schemas"]["QuestionDTO"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Permission */
        Permission: {
            /** Utterance Ref */
            utterance_ref: {
                [key: string]: unknown;
            };
            /** Recording Allowed */
            recording_allowed: boolean;
        };
        /** Person */
        Person: {
            /** Actor Id */
            actor_id: string;
            /** Display Name */
            display_name: string;
        };
        /** Prepare */
        Prepare: {
            /** Subject Id */
            subject_id: string;
            /** Recipient Id */
            recipient_id: string;
            /**
             * Lang
             * @enum {string}
             */
            lang: "fi" | "sv" | "en";
            /** Expected Content Epoch */
            expected_content_epoch: number;
            /** Expected Consent Version */
            expected_consent_version: number;
        };
        /** PublicItem */
        PublicItem: {
            /** Item Id */
            item_id: string;
            /** Topic */
            topic: string;
            /** Statement */
            statement: string;
            /**
             * Status
             * @enum {string}
             */
            status: "observed" | "confirmed" | "none";
            /**
             * Claim Type
             * @enum {string}
             */
            claim_type: "unattributed_statement" | "resident_statement" | "staff_observation" | "sensor_observation" | "plan" | "contact_plan";
            /** Observed At */
            observed_at: string;
            /** Action Status */
            action_status: ("planned" | "confirmed") | null;
            /** Evidence Handle */
            evidence_handle: string;
        };
        /** QuestionCreate */
        QuestionCreate: {
            /** Text */
            text: string;
            /** Topic Hint */
            topic_hint?: string | null;
        };
        /** QuestionDTO */
        QuestionDTO: {
            /** Question Id */
            question_id: string;
            /** Subject Id */
            subject_id: string;
            /** Text */
            text: string;
            /**
             * Status
             * @enum {string}
             */
            status: "received" | "scheduled" | "unanswered" | "answered";
            /** Review Due */
            review_due: string | null;
            /** Updated At */
            updated_at: string;
            /** Revision */
            revision: number;
            /** Answer Available */
            answer_available: boolean;
            /** Display State */
            display_state: string;
            /** Assigned To Display */
            assigned_to_display?: string | null;
            /** Created At */
            created_at: string;
            /** Author Display */
            author_display: string;
            reply?: components["schemas"]["QuestionReply"] | null;
        };
        /** QuestionReply */
        QuestionReply: {
            /** Author Display */
            author_display: string;
            /** Published At */
            published_at: string;
            /** Items */
            items: components["schemas"]["QuestionReplyItem"][];
        };
        /** QuestionReplyItem */
        QuestionReplyItem: {
            /** Statement */
            statement: string;
            /** Claim Type */
            claim_type: string;
        };
        /** Reason */
        Reason: {
            /** Reason Code */
            reason_code: string;
        };
        /** Reject */
        Reject: {
            /** Reason Code */
            reason_code: string;
        };
        /** Response[EvidencePreviewDTO] */
        Response_EvidencePreviewDTO_: {
            data: components["schemas"]["EvidencePreviewDTO"];
            meta: components["schemas"]["Meta"];
        };
        /** Response[FamilyBoardDTO] */
        Response_FamilyBoardDTO_: {
            data: components["schemas"]["FamilyBoardDTO"];
            meta: components["schemas"]["Meta"];
        };
        /** Response[JobDTO] */
        Response_JobDTO_: {
            data: components["schemas"]["JobDTO"];
            meta: components["schemas"]["Meta"];
        };
        /** Response[Page[QuestionDTO]] */
        Response_Page_QuestionDTO__: {
            data: components["schemas"]["Page_QuestionDTO_"];
            meta: components["schemas"]["Meta"];
        };
        /** Response[QuestionDTO] */
        Response_QuestionDTO_: {
            data: components["schemas"]["QuestionDTO"];
            meta: components["schemas"]["Meta"];
        };
        /** Revoke */
        Revoke: {
            /** Scopes */
            scopes: string[];
            /** Expected Consent Version */
            expected_consent_version: number;
            /** Reason Code */
            reason_code: string;
        };
        /** Schedule */
        Schedule: {
            /** Assigned To */
            assigned_to: string;
            /** Review Due */
            review_due: string;
        };
        /** Segment */
        Segment: {
            /** Segment Id */
            segment_id: string;
            /** Text */
            text: string;
            /**
             * Type
             * @enum {string}
             */
            type: "statement" | "observation" | "plan";
            /**
             * Speaker
             * @enum {string}
             */
            speaker: "resident" | "carer" | "unknown";
            /** Evidence Refs */
            evidence_refs: {
                [key: string]: unknown;
            }[];
            /** Required Scopes */
            required_scopes: string[];
        };
        /** SegmentReview */
        SegmentReview: {
            /** Segment Id */
            segment_id: string;
            /** Meaning Checked */
            meaning_checked: boolean;
            /** Speaker Checked */
            speaker_checked: boolean;
            /** Negation And Tense Checked */
            negation_and_tense_checked: boolean;
            /** Numbers Checked */
            numbers_checked: boolean;
            /** Scopes Checked */
            scopes_checked: boolean;
        };
        /** Sensor */
        Sensor: {
            /**
             * Sensor
             * @enum {string}
             */
            sensor: "door" | "bed";
            /** Window Start */
            window_start: string;
            /** Window End */
            window_end: string;
            /**
             * Coverage
             * @enum {string}
             */
            coverage: "complete" | "incomplete";
            /** Subject Attribution Checked */
            subject_attribution_checked: boolean;
            /** Events */
            events: components["schemas"]["Event"][];
        };
        /** Source */
        Source: {
            /** Occurred At */
            occurred_at: string;
            /**
             * Source Type
             * @default staff_note
             * @constant
             */
            source_type: "staff_note";
            /** Text */
            text: string;
            /**
             * Speaker
             * @enum {string}
             */
            speaker: "resident" | "carer" | "unknown";
            /** Required Scopes */
            required_scopes: string[];
            /** Related Source Refs */
            related_source_refs?: {
                [key: string]: unknown;
            }[];
            /**
             * Type
             * @default statement
             * @enum {string}
             */
            type: "statement" | "observation" | "plan";
        };
        /** Subject */
        Subject: {
            /** Subject Id */
            subject_id: string;
            /** Display Name */
            display_name: string;
        };
        /** Tile */
        Tile: {
            /** Topic */
            topic: string;
            /**
             * Display State
             * @enum {string}
             */
            display_state: "available" | "no_record" | "not_shared" | "awaiting_review";
            /** Items */
            items: components["schemas"]["PublicItem"][];
        };
        /** Transcribe */
        Transcribe: {
            /**
             * Language
             * @default fi
             * @enum {string}
             */
            language: "fi" | "en" | "sv" | "ko";
            /** Occurred At */
            occurred_at?: string | null;
        };
        /** Transcript */
        Transcript: {
            /** Occurred At */
            occurred_at: string;
            /** Utterances */
            utterances: components["schemas"]["Utterance"][];
        };
        /** Utterance */
        Utterance: {
            /**
             * Speaker
             * @enum {string}
             */
            speaker: "resident" | "carer" | "unknown";
            /** Text */
            text: string;
            /**
             * Type
             * @default statement
             * @enum {string}
             */
            type: "statement" | "observation" | "plan";
            /** Required Scopes */
            required_scopes?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Wording */
        Wording: {
            /** Item Id */
            item_id: string;
            /** Statement */
            statement: string;
        };
        /** Confirm */
        medipencil__consents__Confirm: {
            /** Recipient Id */
            recipient_id: string;
            /** Confirmed Scopes */
            confirmed_scopes: string[];
            /** Expected Consent Version */
            expected_consent_version: number;
            /** Speaker And Scope Checked */
            speaker_and_scope_checked: boolean;
        };
        /** Publish */
        medipencil__family_events__Publish: {
            /** Recipients */
            recipients: string[];
            /** Reviewed */
            reviewed: boolean;
        };
        /** Confirm */
        medipencil__publications__Confirm: {
            /** Confirmation Ref */
            confirmation_ref: {
                [key: string]: unknown;
            };
            /** Meaning Checked */
            meaning_checked: boolean;
        };
        /** Edit */
        medipencil__publications__Edit: {
            /** Item Edits */
            item_edits: components["schemas"]["Wording"][];
        };
        /** Publish */
        medipencil__publications__Publish: {
            /** Reviewed Items */
            reviewed_items: components["schemas"]["ItemReview"][];
            /** Accepted Answer Candidate Ids */
            accepted_answer_candidate_ids: string[];
            /** Expected Content Epoch */
            expected_content_epoch: number;
            /** Expected Consent Version */
            expected_consent_version: number;
        };
        /** Edit */
        medipencil__records__Edit: {
            /** Version */
            version: number;
            /** Segments */
            segments: components["schemas"]["Segment"][];
            /** Candidate Reviews */
            candidate_reviews?: components["schemas"]["CandidateReview"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_demo_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_demo_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    who_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    residents_api_v1_staff_residents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    residents_api_v1_family_residents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sharing_api_v1_family_residents__s__sharing_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    questions_api_v1_family_residents__s__questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_Page_QuestionDTO__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_family_residents__s__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_QuestionDTO_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_api_v1_staff_question_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    schedule_api_v1_staff_questions__q__schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                q: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Schedule"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unanswered_api_v1_staff_questions__q__mark_unanswered_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                q: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_api_v1_staff_residents__s__captures_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Capture"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    text_api_v1_staff_captures__c__text_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                c: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transcript"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_api_v1_staff_captures__c__drafts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                c: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Draft"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_JobDTO_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_v1_staff_jobs__j__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                j: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_JobDTO_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_api_v1_staff_records__r__get: {
        parameters: {
            query: {
                version: number;
            };
            header?: never;
            path: {
                r: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_api_v1_staff_records__r__draft_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                r: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["medipencil__records__Edit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_staff_records__r__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                r: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Approve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_v1_staff_residents__s__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_api_v1_staff_residents__s__sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Source"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actions_api_v1_staff_residents__s__actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_capture_api_v1_staff_captures__c__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                c: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_status_api_v1_staff_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    review_api_v1_staff_residents__s__emr_review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_bundle_api_v1_staff_residents__s__emr_review_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    context_api_v1_staff_residents__s__publication_context_get: {
        parameters: {
            query: {
                recipient_id: string;
            };
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_api_v1_staff_publications_prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Prepare"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_JobDTO_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pub_api_v1_staff_publications__p__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_api_v1_staff_publications__p__draft_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["medipencil__publications__Edit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_staff_publications__p__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                p: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["medipencil__publications__Publish"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_api_v1_family_residents__s__board_get: {
        parameters: {
            query?: {
                lang?: "fi" | "sv" | "en";
            };
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_FamilyBoardDTO_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_api_v1_family_items__item__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response_EvidencePreviewDTO_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_v1_staff_actions__a__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                a: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["medipencil__publications__Confirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listing_api_v1__role__residents__s__family_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: "staff" | "family";
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_events_api_v1_staff_residents__s__family_events_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Import"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_staff_family_events__eid__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["medipencil__family_events__Publish"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_api_v1_staff_family_events__eid__withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_api_v1_family_family_events__eid__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_staff_residents__s__dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_family_residents__s__dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consents_api_v1_staff_residents__s__consents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidate_api_v1_staff_residents__s__consent_candidates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Candidate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_v1_staff_consent_candidates__c__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                c: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["medipencil__consents__Confirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_v1_staff_consent_candidates__c__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                c: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reject"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_v1_staff_residents__s__consents__recipient__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
                recipient: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Revoke"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_api_v1_staff_records__r__corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                r: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Correction"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    permission_api_v1_staff_residents__s__recording_permissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Permission"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_v1_staff_captures__c__audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                c: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_v1_staff_captures__c__audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_api_v1_staff_captures__c__transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                c: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Transcribe"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_staff_captures__c__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                c: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_staff_captures__c__audio_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                c: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_v1_staff_captures__c__retry_cleanup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                c: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sensor_api_v1_staff_residents__s__sensor_observations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                s: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Sensor"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listing_api_v1_poc_comments_get: {
        parameters: {
            query?: {
                screen?: ("general" | "family" | "questions" | "record" | "publication" | "consent") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_poc_comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
