import {useState} from 'react';
import {api} from './api';
import {stateLabel} from './labels';
type Pub={publication_id:string;revision:number;status:string;content_epoch:number;consent_version:number;items:{item_id:string;statement:string;claim_type:string}[];answer_bindings:{candidate_id:string}[]};
export function Publication(){
 const [recipient,setRecipient]=useState('liisa'),[pub,setPub]=useState<Pub|null>(null),[checked,setChecked]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function prepare(){setBusy(true);setPub(null);setChecked(false);setError('');try{const ctx=await api<{content_epoch:number;consent_version:number}>(`/staff/residents/aino/publication-context?recipient_id=${recipient}`);const job=await api<{result_ref:{id:string}}>('/staff/publications/prepare',{subject_id:'aino',recipient_id:recipient,lang:'fi',expected_content_epoch:ctx.content_epoch,expected_consent_version:ctx.consent_version});setPub(await api<Pub>(`/staff/publications/${job.result_ref.id}`));}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function publish(){if(!pub||!checked)return;setBusy(true);try{setPub(await api<Pub>(`/staff/publications/${pub.publication_id}/publish`,{reviewed_items:pub.items.map(i=>({item_id:i.item_id,meaning_checked:checked,language_checked:checked,evidence_checked:checked})),accepted_answer_candidate_ids:pub.answer_bindings.map(b=>b.candidate_id),expected_content_epoch:pub.content_epoch,expected_consent_version:pub.consent_version},pub.revision));}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <section><h2>4 · Tarkista ja julkaise perheelle</h2><label>Vastaanottaja<select value={recipient} onChange={e=>{setRecipient(e.target.value);setPub(null);setChecked(false);}}><option value="liisa">Liisa</option><option value="mikko">Mikko</option></select></label><button disabled={busy} onClick={()=>void prepare()}>Valmistele julkaisu</button>{error&&<p role="alert">{error}</p>}{pub&&<article><h3>Esikatselu · {recipient} · {stateLabel[pub.status]}</h3>{pub.items.map(i=><p key={i.item_id}>{i.statement} <small>{stateLabel[i.claim_type]}</small></p>)}{pub.status==='draft'&&<><label><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Tarkistin jokaisen lauseen merkityksen, lähteen, suomen kielen ja vastauksen riittävyyden.</label><button disabled={!checked||busy} onClick={()=>void publish()}>Julkaise hyväksytty vastaus</button></>}{pub.status==='published'&&<p role="status" aria-label="Julkaisun tila">Julkaistu. Perheen näkymä tarkistaa oikeudet uudelleen.</p>}</article>}</section>;
}
