# Immutable schema for revision 001. Future changes use new migrations.
SCHEMA = '''
CREATE TABLE units(unit_id TEXT PRIMARY KEY, name TEXT NOT NULL, contact_config_json TEXT NOT NULL DEFAULT '{}', contact_verified_by TEXT, contact_verified_at TEXT);
CREATE TABLE actors(actor_id TEXT PRIMARY KEY, role TEXT NOT NULL CHECK(role IN ('family','staff','demo_admin')), display_name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE residents(subject_id TEXT PRIMARY KEY, unit_id TEXT NOT NULL REFERENCES units, display_name TEXT NOT NULL, room_label TEXT, care_order INTEGER NOT NULL DEFAULT 0, content_epoch INTEGER NOT NULL DEFAULT 1, data_origin TEXT NOT NULL CHECK(data_origin='TEAM_SYNTHETIC'));
CREATE TABLE access_memberships(subject_id TEXT REFERENCES residents, actor_id TEXT REFERENCES actors, can_ask INTEGER NOT NULL DEFAULT 0, can_review INTEGER NOT NULL DEFAULT 0, can_manage_consent INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(subject_id,actor_id));
CREATE TABLE demo_sessions(session_hash TEXT PRIMARY KEY, actor_id TEXT NOT NULL REFERENCES actors, csrf_hash TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE source_events(source_id TEXT, version INTEGER NOT NULL, subject_id TEXT NOT NULL REFERENCES residents, source_type TEXT NOT NULL, occurred_at TEXT NOT NULL, recorded_at TEXT NOT NULL, data_origin TEXT NOT NULL, integration_mode TEXT NOT NULL, payload_json TEXT NOT NULL, source_refs_json TEXT NOT NULL DEFAULT '[]', valid INTEGER NOT NULL DEFAULT 1, invalidated_at TEXT, PRIMARY KEY(source_id,version));
CREATE TABLE captures(capture_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL REFERENCES residents, actor_id TEXT NOT NULL REFERENCES actors, input_mode TEXT NOT NULL, status TEXT NOT NULL, source_refs_json TEXT NOT NULL DEFAULT '[]', audio_ref TEXT, disclosure_ack_at TEXT, recording_permission_ref TEXT, error_code TEXT, revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE processing_jobs(job_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL REFERENCES residents, job_type TEXT NOT NULL, status TEXT NOT NULL, target_id TEXT NOT NULL, expected_revision INTEGER NOT NULL, input_refs_json TEXT NOT NULL, result_ref TEXT, provider_id TEXT, execution_meta_json TEXT NOT NULL, deadline_at TEXT NOT NULL, canceled_at TEXT, error_code TEXT, revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE record_versions(record_id TEXT, version INTEGER, subject_id TEXT NOT NULL REFERENCES residents, capture_id TEXT REFERENCES captures, status TEXT NOT NULL, segments_json TEXT NOT NULL, reviewed_by TEXT REFERENCES actors, approved_at TEXT, supersedes_version INTEGER, correction_reason TEXT, revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(record_id,version), CHECK(status != 'approved' OR (reviewed_by IS NOT NULL AND approved_at IS NOT NULL)));
CREATE TABLE family_questions(question_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL REFERENCES residents, recipient_id TEXT NOT NULL REFERENCES actors, text TEXT NOT NULL, assigned_to TEXT REFERENCES actors, status TEXT NOT NULL, review_due TEXT, active_publication_id TEXT REFERENCES publications, status_reason TEXT, revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE answer_candidates(candidate_id TEXT PRIMARY KEY, question_id TEXT NOT NULL REFERENCES family_questions, record_id TEXT NOT NULL, record_version INTEGER NOT NULL, answer_segment_ids_json TEXT NOT NULL, review_status TEXT NOT NULL, reviewed_by TEXT REFERENCES actors, reviewed_at TEXT, FOREIGN KEY(record_id,record_version) REFERENCES record_versions);
CREATE TABLE care_actions(action_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL REFERENCES residents, description TEXT NOT NULL, status TEXT NOT NULL, planned_in_json TEXT NOT NULL, confirmed_in_json TEXT, review_required INTEGER NOT NULL DEFAULT 0, revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE consent_candidates(candidate_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL REFERENCES residents, recipient_id TEXT REFERENCES actors, proposed_scopes_json TEXT NOT NULL, utterance_ref_json TEXT NOT NULL, disposition TEXT NOT NULL, reviewed_by TEXT REFERENCES actors, reviewed_at TEXT, revision INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE consent_versions(consent_id TEXT, version INTEGER, subject_id TEXT NOT NULL REFERENCES residents, recipient_id TEXT NOT NULL REFERENCES actors, status TEXT NOT NULL, scopes_json TEXT NOT NULL, confirmed_by TEXT NOT NULL REFERENCES actors, confirmed_at TEXT NOT NULL, revoked_at TEXT, evidence_ref_json TEXT NOT NULL, derived_from_candidate_id TEXT REFERENCES consent_candidates, PRIMARY KEY(consent_id,version), UNIQUE(subject_id,recipient_id,version));
CREATE TABLE publications(publication_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL REFERENCES residents, recipient_id TEXT NOT NULL REFERENCES actors, lang TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL, consent_version INTEGER NOT NULL, content_epoch INTEGER NOT NULL, items_json TEXT NOT NULL, answer_bindings_json TEXT NOT NULL, input_refs_json TEXT NOT NULL, generation_meta_json TEXT NOT NULL, reviewed_by TEXT REFERENCES actors, published_at TEXT, invalidated_at TEXT, invalidation_reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE audio_cleanup_jobs(cleanup_id TEXT PRIMARY KEY, capture_id TEXT NOT NULL REFERENCES captures, artifact_refs_json TEXT NOT NULL, deletion_status TEXT NOT NULL, deleted_at TEXT, trigger TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, next_retry_at TEXT, receipts_json TEXT NOT NULL, CHECK((deletion_status='deleted') = (deleted_at IS NOT NULL)));
CREATE TABLE audit_events(audit_id TEXT PRIMARY KEY, actor_id TEXT REFERENCES actors, action TEXT NOT NULL, subject_id TEXT REFERENCES residents, object_id TEXT NOT NULL, object_version INTEGER, timestamp TEXT NOT NULL, outcome TEXT NOT NULL, request_id TEXT NOT NULL, reason_code TEXT);
CREATE TABLE idempotency_keys(actor_id TEXT REFERENCES actors, route_key TEXT, request_key TEXT, request_digest TEXT NOT NULL, object_ref_json TEXT, result_status INTEGER, state TEXT NOT NULL, expires_at TEXT NOT NULL, PRIMARY KEY(actor_id,route_key,request_key));
CREATE INDEX question_queue ON family_questions(subject_id,status,review_due,created_at);
CREATE INDEX source_time ON source_events(subject_id,occurred_at);
CREATE INDEX publication_pair ON publications(subject_id,recipient_id,lang,published_at);
CREATE INDEX jobs_deadline ON processing_jobs(status,deadline_at);
CREATE INDEX cleanup_retry ON audio_cleanup_jobs(deletion_status,next_retry_at);
'''
TRIGGERS = [
'''CREATE TRIGGER source_immutable BEFORE UPDATE OF payload_json,source_refs_json,subject_id,occurred_at,recorded_at,data_origin,integration_mode ON source_events BEGIN SELECT RAISE(ABORT,'immutable source'); END''',
'''CREATE TRIGGER approved_immutable BEFORE UPDATE OF segments_json,subject_id ON record_versions WHEN OLD.status!='draft' BEGIN SELECT RAISE(ABORT,'immutable record'); END''',
'''CREATE TRIGGER consent_immutable BEFORE UPDATE ON consent_versions BEGIN SELECT RAISE(ABORT,'immutable consent'); END'''
]
