"""Export the in-app manual as matching offline Markdown guides."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[2]
content=json.loads((root/'apps/web/src/manual-content.json').read_text())
for language,sections in content.items():
    title='사용자 매뉴얼' if language=='ko' else 'User manual'
    lines=[f'# MediPencil · {title}', '', '2026-10-04 · https://orch.sungah.kr/medipencil/manual', '', '<!-- Generated by tools/dev/export_manual.py from apps/web/src/manual-content.json. -->', '']
    for section in sections:
        lines += ['## '+section['title'],'']
        for paragraph in section['paragraphs']:lines += [paragraph,'']
        for i,step in enumerate(section['steps'],1):lines += [f'{i}. {step}']
        if section['steps']:lines += ['']
        if section['table']:
            for i,row in enumerate(section['table']):
                lines += ['| '+' | '.join(cell.replace('|','\\|') for cell in row)+' |']
                if i==0:lines += ['| '+' | '.join('---' for _ in row)+' |']
            lines += ['']
        for note in section['notes']:lines += ['> '+note,'']
    (root/f'docs/poc/user-manual.{language}.md').write_text('\n'.join(lines))
